version: '3.8'
services:
  base:
    image: deb-base
    env_file:
      - .env
    build: 
      context: ${CONTEXT}
      dockerfile: ${CONTEXT}/base/dockerfile
  dns:
    container_name: dnssrv
    image: bind9
    env_file:
      - .env
    build:
      context: ${CONTEXT}
      dockerfile: ${CONTEXT}/dns/dockerfile
    ports:
      - "2101:${SSH_PORT}"
      - "${DNS_PORT}:${DNS_PORT}/tcp"
      - "${DNS_PORT}:${DNS_PORT}/udp"
    volumes:
      - ./zonas:/var/cache/bind:rw
      - ./logs:/root/logs:rw
    networks:
      netddns:
        ipv4_address: 172.16.1.2
  dhcp:
    container_name: dhcpsrv
    image: isc-dhcp-server
    env_file:
      - .env
    build:
      context: ${CONTEXT}
      dockerfile: ${CONTEXT}/dhcp/dockerfile
    ports:
      - "2102:${SSH_PORT}"
    volumes:
      - ./leases:/var/lib/dhcp:rw
      - ./logs:/root/logs:rw
    networks:
      netddns:
        ipv4_address: 172.16.1.3
  http:
    container_name: logssrv
    image: logshttp
    env_file:
      - .env
    build:
      context: ${CONTEXT}
      dockerfile: ${CONTEXT}/http/dockerfile
    ports:
      - "2103:${SSH_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - ./logs:/var/www/html:rw
    networks:
      netlogs:
        ipv4_address: 172.16.2.2
networks:
  netlogs:
    external: true
  netddns:
    external: true