version: '3.8'
services:
  dns:
    container_name: dnssrv
    image: bind9
    env_file:
      - .env
    build:
      context: ${CONTEXT}
      dockerfile: ${CONTEXT}/dns/dockerfile
    ports:
      - "2101:${SSH_PORT}"
    volumes:
      - dns_bind_vol:/etc/bind:ro
      - dns_zonas_vol:/var/cache/bind:rw
    networks:
      netddns:
        ipv4_address: 172.16.1.2
networks:
  netddns:
    ipam:
      driver: default
      config: 
        - subnet: 172.16.1.0/24
volumes:
  dns_bind_vol:
    external: true
  dns_zonas_vol:
    external: true