version: '3.8'
services:
  base:
    image: deb-base
    env_file:
      - .env
    build: 
      context: ${CONTEXT}
      dockerfile: ${CONTEXT}/base/dockerfile
  dns:
    container_name: dnssrv
    image: bind9
    env_file:
      - .env
    build:
      context: ${CONTEXT}
      dockerfile: ${CONTEXT}/dns/dockerfile
    ports:
      - "2101:${SSH_PORT}"
      - "${DNS_PORT}:${DNS_PORT}/tcp"
      - "${DNS_PORT}:${DNS_PORT}/udp"
    volumes:
      - dns_bind_vol:/etc/bind:ro
      - dns_zonas_vol:/var/cache/bind:rw
      - ./scripts:/root/scripts:ro
    networks:
      netddns:
        ipv4_address: 172.16.1.2
  dhcp:
    container_name: dhcpsrv
    image: isc-dhcp-server
    env_file:
      - .env
    build:
      context: ${CONTEXT}
      dockerfile: ${CONTEXT}/dhcp/dockerfile
    ports:
      - "2102:${SSH_PORT}"
    volumes:
      - dhcp_vol:/etc/dhcp:ro
      - dhcp_leases_vol:/var/lib/dhcp:rw
      - ./scripts:/root/scripts:ro
    networks:
      netddns:
        ipv4_address: 172.16.1.3
networks:
  netddns:
    external: true
volumes:
  dns_bind_vol:
    external: true
  dns_zonas_vol:
    external: true
  dhcp_vol:
    external: true
  dhcp_leases_vol:
    external: true