# Dockerfile para el servicio DNS
# Partimos de la imagen base
FROM deb-base  

# PAQUETERÍA
# Instalación de los paquetes necesarios
RUN apt install -yq --no-install-recommends \
    # Servicio DNS
    bind9 \
    dnsutils \
    geoip-bin \
    bind9-doc \
    # Eliminar paquetes huérfanos
    && apt autoremove -y \
    # Limpiar caché de apt
    && apt clean

# Se situa en la carpeta de los scripts
WORKDIR /root/scripts

# SCRIPTS DE CONFIGURACIÓN
# Copiar los scripts al contenedor
COPY ./scripts/base ./base
COPY ./scripts/dns ./dns
# Conceder permisos de ejecución a los scripts
RUN chmod u+x ./* -R

# Exponer puertos DNS
EXPOSE 53/tcp
EXPOSE 53/udp

# Ejecutar el script de inicio del servicio DNS
ENTRYPOINT [ "/root/scripts/dns/start_dns.sh" ]