# Dockerfile para el servicio DDNS
# Partimos de la imagen base
FROM deb-base  

ENV DNS_PORT=53

# PAQUETERÍA
# Instalación de los paquetes necesarios
RUN apt install -yq --no-install-recommends \
    # Servicio DNS
    bind9 \
    dnsutils \
    geoip-bin \
    # Eliminar paquetes huérfanos
    && apt autoremove -yq \
    # Limpiar caché de apt
    && apt clean -yq

# Se situa en la carpeta de los scripts
WORKDIR /root/scripts

# SCRIPTS DE CONFIGURACIÓN
# Copiar los scripts al contenedor
# COPY ./scripts/base ./base
# COPY ./scripts/dns ./dns
# Conceder permisos de ejecución a los scripts
# RUN chmod u+x ./* -R

COPY ./bind /etc/bind

# Exponer puertos DNS
EXPOSE ${DNS_PORT}
EXPOSE ${DNS_PORT}/udp

# Ejecutar el script de inicio del servicio DNS
ENTRYPOINT [ "/root/scripts/dns/start_dnsd.sh" ]