# Dockerfile para el servicio HTTP
# Partimos de la imagen base
FROM deb-base  

ENV HTTP_PORT=80

# PAQUETERÍA
# Instalación de los paquetes necesarios
RUN apt install -yq --no-install-recommends \
    # Servicio HTTP
    apache2 \
    apache2-utils \
    # Eliminar paquetes huérfanos
    && apt autoremove -yq \
    # Limpiar caché de apt
    && apt clean -yq

# Se situa en la carpeta de los scripts
WORKDIR /root/scripts

# SCRIPTS DE CONFIGURACIÓN
# Copiar los scripts al contenedor
# COPY ./scripts/base ./base
# COPY ./scripts/http ./http
# Conceder permisos de ejecución a los scripts
# RUN chmod u+x ./* -R

COPY ./config/apache2.conf /etc/apache2/

# Exponer puertos HTTP
EXPOSE ${HTTP_PORT}

# Ejecutar el script de inicio del servicio HTTP
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
#ENTRYPOINT [ "/root/scripts/http/start_httpd.sh" ]