version: '3.8'
services:
  dns:
    container_name: dnsrv
    image: bind9-hlc
    environment:
      - LOG=/root/logs/dnsrv.html
      - TITULO=LOG DNSSRV
      - TITULO_INFORME=INFORME DEL CONTENEDOR DNSRV
    env_file:
      - environment.yml
    build:
      context: $CONTEXT
      dockerfile: $DNS_DOCKERFILE/Dockerfile
      args:
        DNS_PORT: $DNS_PORT
        DNS_DOCKERFILE: $DNS_DOCKERFILE
        IDRSA: $IDRSA
    ports:
      - "2201:$SSH_PORT"
      - "$DNS_PORT:$DNS_PORT/tcp"
      - "$DNS_PORT:$DNS_PORT/udp"
    volumes:
      - ./dns_hlc/zonas:/var/cache/bind:rw
      - ./logs:/root/logs:rw
    networks:
      default:
        ipv4_address: 172.16.1.2
  dhcp:
    container_name: dhcpsrv
    image: isc-dhcp-hlc
    environment:
      - LOG=/root/logs/dhcpsrv.html
      - TITULO=LOG DHCPSRV
      - TITULO_INFORME=INFORME DEL CONTENEDOR DHCPSRV
    env_file:
      - environment.yml
    build:
      context: $CONTEXT
      dockerfile: $DHCP_DOCKERFILE/Dockerfile
      args:
        DHCP_PORT: $DHCP_PORT
        DHCP_DOCKERFILE: $DHCP_DOCKERFILE
        IDRSA: $IDRSA
    volumes:
      - ./dhcp_hlc/leases:/var/lib/dhcp:rw
      - ./logs:/root/logs:rw
    network_mode: host
  web_logs:
    container_name: logsrv
    image: web_logs
    environment:
      - LOG=/var/www/html/logsrv.html
      - TITULO=LOG LOGSRV
      - TITULO_INFORME=INFORME DEL CONTENEDOR LOGSRV
    env_file:
      - environment.yml
    build:
      context: $CONTEXT
      dockerfile: $HTTP_DOCKERFILE/Dockerfile
      args:
        HTTP_PORT: $HTTP_PORT
        HTTP_DOCKERFILE: $HTTP_DOCKERFILE
        IDRSA: $IDRSA
    ports:
      - "2203:$SSH_PORT"
      - "$HTTP_PORT:$HTTP_PORT"
    volumes:
      - ./logs:/var/www/html:rw
    networks:
      default:
        ipv4_address: 172.16.1.3
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24