# Dockerfile para el servicio DHCP
# Partimos de la imagen base
FROM deb-base  

ENV DHCP_PORT=67

# PAQUETERÍA
# Instalación de los paquetes necesarios
RUN apt install -yq --no-install-recommends \
    # Servicio DHCP
    isc-dhcp-server \
    dhcping \
    dhcpd-pools \
    # Eliminar paquetes huérfanos
    && apt autoremove -yq \
    # Limpiar caché de apt
    && apt clean -yq

# Se situa en la carpeta de los scripts
WORKDIR /root/scripts

# SCRIPTS DE CONFIGURACIÓN
# Copiar los scripts al contenedor
# COPY ./scripts/base ./base
# COPY ./scripts/dhcp ./dhcp
# Conceder permisos de ejecución a los scripts
# RUN chmod u+x ./* -R

# DHCPD.CONF
COPY ./config/dhcpd.conf /etc/dhcp

# Exponer puertos DHCP
EXPOSE ${DHCP_PORT}/udp

# Ejecutar el script de inicio del servicio DHCP
ENTRYPOINT [ "/root/scripts/dhcp/start_dhcpd.sh" ]