# Dockerfile para el servicio DHCP
# Partimos de la imagen base de debian
FROM deb-base

# PAQUETERÍA
# Instalación de los paquetes necesarios
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -yq --no-install-recommends \
    # Servicio DHCP
    isc-dhcp-server

# SCRIPTS
# Copiar los scripts al contenedor
COPY ./dhcp/start_dhcp.sh /root
COPY ./dhcp/scriptsDHCP /root/scriptsDHCP
# Conceder permisos de ejecución a los scripts
RUN chmod u+x /root/start_dhcp.sh
RUN chmod u+x /root/scriptsDHCP -R

# Exponer puertos DHCP
EXPOSE 67/udp

# Ejecutamos el script de inicio del servicio SSH
ENTRYPOINT [ "/root/start_dhcp.sh" ]
