# Dockerfile imagen base de debian
FROM debian

ENV TZ='Europe/Madrid'
ENV SSH_PORT=2222

# Establecer la zona horaria
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# PAQUETERÍA
# Actualizar lista de paquetes, actualizar paquetes y instalación de los paquetes necesarios
RUN apt update && apt upgrade -y && apt install -yq --no-install-recommends \
    # Utilidades
    apt-utils \
    # Gestión de ficheros
    tree \
    locate \
    vim \
    # Seguridad
    sudo \
    # Red
    iputils-ping \
    iproute2 \
    openssh-server \
    iptables \
    iptables-persistent \
    net-tools \
    # Automatización
    expect

# Copiar clave rsa para el autentificado sin contraseña del servicio SSH
COPY ./claves/id_rsa.pub /root

# Se situa en la carpeta root
WORKDIR /root
# Crea los directorios para el almacenaje de los logs y los scripts de configuración
RUN mkdir logs scripts

# Exponer puerto ssh
EXPOSE ${SSH_PORT}