# Dockerfile imagen base de debian
FROM debian

# Variables de entorno en el dockerfile
ENV TZ='Europe/Madrid'
ENV SSH_PORT=2222

# Establecer la zona horaria
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && echo ${TZ} > /etc/timezone

# PAQUETERÍA
# Actualizar lista de paquetes, actualizar paquetes y instalación de los paquetes bases
RUN apt update && apt upgrade -y && apt install -yq --no-install-recommends \
    # Utilidades
    apt-utils \
    # Gestión de ficheros
    tree \
    locate \
    vim \
    # Seguridad
    sudo \
    # Red
    iputils-ping \
    iproute2 \
    openssh-server \
    iptables \
    iptables-persistent \
    net-tools

# Copiar clave rsa para el autentificado sin contraseña del servicio SSH
COPY ./claves_rsa/id_rsa.pub /root

# Trabajar en la carpeta /root
WORKDIR /root

# Crear los directorios para el almacenaje de los logs y los scripts de configuración
RUN mkdir logs scripts

# SCRIPTS DE CONFIGURACIÓN
# Copiar los scripts de configuración base al contenedor
COPY ./scripts/base ./scripts/base
# Copiar los scripts de generado de los logs
COPY ./scripts/logs ./scripts/logs

# Exponer puerto ssh
EXPOSE ${SSH_PORT}